name: NuGet Publish

on:
  push:
    branches: [ master ]

jobs:
  nuget-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.412
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        mkdir __out
        dotnet pack -c Release -o __out --no-restore
        dotnet nuget push "./__out/*.nupkg" --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_TOKEN}}
        rm -rf __out
